### ISSUE TITLE
issue in overlapsWithPlottedPoints

### ISSUE THREAD

**Issue by LeopoldC** [JosephCrispell/basicPlotteR#2]
Hey,
I just Try pretty fast your code for my own plot, with few set of point I had an issue, as an example I ran a plot with:

Y=c(0.670057038012,0.73204100355,0.708547724463,0.670057038012,0.708547724463,0.708547724463,0.73204100355,0.745083961549,0.670057038012,0.735112281122,0.670057038012,0.670057038012,0.670057038012,0.670057038012,0.708547724463,0.659367396594)
X=c(0.227223557992,0.225535290825,0.196770791161,0.2246476946,0.22171406086,0.196770791161,0.225535290824,0.302982095831,0.183715286292,0.220484997556,0.2246476946,0.2246476946,0.183715286292,0.227223557992,0.234154197748,-0.00171678767261)

Error in if (abs(x - pointInfo$X[i]) < width && abs(y - pointInfo$Y[i]) <  : 
  valeur manquante là où TRUE / FALSE est requis

I didn't check more but it seems that the function doesn't work well with point that are pretty close
Best
Léopold

**Comment by JosephCrispell** [comment]
Hi Léopold,

Thanks for using the tool! I think you might be using it incorrectly, you have to plot the points before you can use my `addTextLabels()` function. The code below works well for your example points:

    # Load the library
    library(plotteR)

    # Create some test data
    Y <- c(0.670057038012,0.73204100355,0.708547724463,0.670057038012,0.708547724463,0.708547724463,0.73204100355,0.745083961549,0.670057038012,0.735112281122,0.670057038012,0.670057038012,0.670057038012,0.670057038012,0.708547724463,0.659367396594)
    X <- c(0.227223557992,0.225535290825,0.196770791161,0.2246476946,0.22171406086,0.196770791161,0.225535290824,0.302982095831,0.183715286292,0.220484997556,0.2246476946,0.2246476946,0.183715286292,0.227223557992,0.234154197748,-0.00171678767261)

    # Create some test labels
    myTestLabels <- sample(c("short", "medium", "loonnngggg"), length(Y), replace=TRUE)

    # Plot the data as a scatter plot
    plot(x=X, y=Y, pch=19, bty="n", col="red", xlab="X", ylab="Y")
    addTextLabels(X, Y, myTestLabels, cex=1, col.label="black")

Here is the output the above code produces:
![image](https://user-images.githubusercontent.com/17436210/58200946-dd07ec00-7ccb-11e9-9879-6e02f212e068.png)

Let me know if this makes sense or I have misunderstood your issue. 

Thanks again for using the tool! :-)

**Comment by LeopoldC** [comment]
Hey, here was the function that I use :

PlotJBresBinary<-function(X,Y,X2,Y2,outname){
	png(outname,width = 600, height = 600, units = "px")
	par(cex.lab=2,cex.axis=2,mgp=c(6,1,0),mar=c(8.1, 8.1, 4.1, 2.1),cex.main=2)
	XLIMV=c(min(X-0.1,X2-0.1),max(X+0.1,X2+0.1))
	YLIMV=c(min(Y-0.1,Y2-0.1),max(Y+0.1,Y2+0.1))
	plot(X,Y,col="dodgerblue",pch=16,xlab="X",ylab="Y",main="Values",xlim=XLIMV,ylim=YLIMV,cex=2)
	points(X2,Y2,col="firebrick4",pch=16,cex=2)
	#legend("topleft",MyLegend,pch=c(16,16),col=c("dodgerblue","firebrick4"),cex=2)	
	addTextLabels(X, Y, labels=LabelsR,cex=1.2)
	#text(X2+0.01, Y2+0.01, labels=LabelsR,cex=1.2)
	dev.off()
}

I mainly thought that the addition of other points will block it, but still I your code work for some set of value and some not, I will try to find why. But I produce some good graph with your code before make this ticket!

**Comment by JosephCrispell** [comment]
Hi Léopold,

Thanks for sending your code, would you mind sending the values you use for your `X2` and `Y2` vectors?

Thanks!

**Comment by LeopoldC** [comment]
Try this set if you want :) : 
Y=c(0.670057038012,0.73204100355,0.708547724463,0.670057038012,0.708547724463,0.708547724463,0.73204100355,0.745083961549,0.670057038012,0.735112281122,0.670057038012,0.670057038012,0.670057038012,0.670057038012,0.708547724463,0.659367396594)
X=c(0.227223557992,0.225535290825,0.196770791161,0.2246476946,0.22171406086,0.196770791161,0.225535290824,0.302982095831,0.183715286292,0.220484997556,0.2246476946,0.2246476946,0.183715286292,0.227223557992,0.234154197748,-0.00171678767261)
Y2=c(0.682461808464,0.676159706434,0.670096924734,0.670096924734,0.687647082286,0.692593035778,0.676279366599,0.687886402617,0.649395716166,0.703681544414)
X2=c(0.342590359106,0.372597218291,0.309552970738,0.309552970738,0.393085243123,0.349114095369,0.380918414289,0.381299522156,0.178095479436,0.461775826666)

**Comment by JosephCrispell** [comment]
Hi Léopold,

Sorry I can't seem to replicate your error using your code and the example data you sent. 

Just to demonstrate, when I run the following code (which includes your function and example code), I get no errors:
    
    # Re-install the plotteR package and load
    #install.packages("devtools")
    devtools::install_github("JosephCrispell/plotteR")
    library(plotteR)

    # Load the plotting function
    PlotJBresBinary<-function(X, Y, X2, Y2, outname){
      png(outname,width = 600, height = 600, units = "px")
  
      par(cex.lab=2,cex.axis=2,mgp=c(6,1,0),mar=c(8.1, 8.1, 4.1, 2.1),cex.main=2)
  
      XLIMV=c(min(X-0.1,X2-0.1),max(X+0.1,X2+0.1))
      YLIMV=c(min(Y-0.1,Y2-0.1),max(Y+0.1,Y2+0.1))
  
      plot(X,Y,col="dodgerblue",pch=16,xlab="X",ylab="Y",main="Values",xlim=XLIMV,ylim=YLIMV,cex=2)
      points(X2,Y2,col="firebrick4",pch=16,cex=2)
  
      #legend("topleft",MyLegend,pch=c(16,16),col=c("dodgerblue","firebrick4"),cex=2)
      addTextLabels(X, Y, labels=LabelsR,cex=1.2)
  
      #text(X2+0.01, Y2+0.01, labels=LabelsR,cex=1.2)
      dev.off()
    }
    
    # Set the working directory
    setwd("/home/josephcrispell/Desktop/")
    
    # Some example data
    Y=c(0.670057038012,0.73204100355,0.708547724463,0.670057038012,0.708547724463,0.708547724463,0.73204100355,0.745083961549,0.670057038012,0.735112281122,0.670057038012,0.670057038012,0.670057038012,0.670057038012,0.708547724463,0.659367396594)
    X=c(0.227223557992,0.225535290825,0.196770791161,0.2246476946,0.22171406086,0.196770791161,0.225535290824,0.302982095831,0.183715286292,0.220484997556,0.2246476946,0.2246476946,0.183715286292,0.227223557992,0.234154197748,-0.00171678767261)
    Y2=c(0.682461808464,0.676159706434,0.670096924734,0.670096924734,0.687647082286,0.692593035778,0.676279366599,0.687886402617,0.649395716166,0.703681544414)
    X2=c(0.342590359106,0.372597218291,0.309552970738,0.309552970738,0.393085243123,0.349114095369,0.380918414289,0.381299522156,0.178095479436,0.461775826666)
    
    # Create some labels
    LabelsR <- sample(c("short", "medium", "loonnngggg"), length(Y), replace=TRUE)
    
    PlotJBresBinary(X,Y, X2, Y2,"test.png")

I get the following plot:
![test](https://user-images.githubusercontent.com/17436210/58251671-18ea9200-7d5c-11e9-98b6-56d8d7bb6c7c.png)

Would you be able to paste the code above into a new script in R and try running it on your computer please? You'll need to change the working directory on line 26 after the `# Set the working directory` comment.

Let me know how you get on. Sorry this is taking a wee while to track down!

**Comment by JosephCrispell** [comment]
It could have something to do with your LabelsR vector, I just created a random one in the code above. If you want you could send me the vallues you use and I can check that.

Thanks,

Joe

**Comment by LeopoldC** [comment]
Okay found it, this bug only append when you give some label of the wrong size to the text, sorry :)
Thanks for the Rubber duck debugging :).

**Comment by JosephCrispell** [comment]
No problem, glad you found it!

**Comment by JosephCrispell** [comment]
I'll add in a quick check into the code to send a more informative error message
